--liquibase formatted sql

--changeset Grigoryev_Pavel:2
INSERT INTO users (nickname, name, email)
VALUES ('alice', 'Alice Smith', 'alice@gmail.com'),
       ('bob', 'Bob Jones', 'bob@yahoo.com'),
       ('charlie', 'Charlie Brown', 'charlie@hotmail.com'),
       ('david', 'David Lee', 'david@outlook.com'),
       ('emma', 'Emma Watson', 'emma@icloud.com'),
       ('frank', 'Frank Sinatra', 'frank@gmail.com'),
       ('grace', 'Grace Kelly', 'grace@yahoo.com'),
       ('harry', 'Harry Potter', 'harry@hotmail.com'),
       ('isabel', 'Isabel Green', 'isabel@outlook.com'),
       ('jack', 'Jack Sparrow', 'jack@icloud.com'),
       ('kate', 'Kate Middleton', 'kate@gmail.com'),
       ('leo', 'Leo Messi', 'leo@yahoo.com'),
       ('maya', 'Maya Angelou', 'maya@hotmail.com'),
       ('nick', 'Nick Fury', 'nick@outlook.com'),
       ('olivia', 'Olivia Wilde', 'olivia@icloud.com'),
       ('peter', 'Peter Parker', 'peter@gmail.com'),
       ('quinn', 'Quinn Fabray', 'quinn@yahoo.com'),
       ('rachel', 'Rachel Berry', 'rachel@hotmail.com'),
       ('sam', 'Sam Wilson', 'sam@outlook.com'),
       ('tina', 'Tina Cohen-Chang', 'tina@icloud.com'),
       ('uma', 'Uma Thurman', 'uma@gmail.com'),
       ('victor', 'Victor Hugo', 'victor@yahoo.com'),
       ('wanda', 'Wanda Maximoff', 'wanda@hotmail.com'),
       ('xavier', 'Xavier Woods', 'xavier@outlook.com'),
       ('yara', 'Yara Greyjoy', 'yara@icloud.com'),
       ('zack', 'Zack Snyder', 'zack@gmail.com'),
       ('anna', 'Anna Karenina', 'anna@yahoo.com'),
       ('ben', 'Ben Affleck', 'ben@hotmail.com'),
       ('clara', 'Clara Oswald', 'clara@outlook.com'),
       ('dan', 'Dan Brown', 'dan@icloud.com');

INSERT INTO channels (name, short_description, author_id, created_at, main_language, avatar, category)
VALUES ('Cooking with Alice', 'Learn how to make delicious dishes with Alice', 1, '2023-01-01 10:00:00', 'English',
        null, 'Food'),
       ('La música de Bob', 'Escucha las canciones originales y las versiones de Bob', 2, '2023-01-02 11:00:00',
        'Spanish', null, 'Music'),
       ('Les bandes dessinées de Charlie', 'Profitez des bandes dessinées drôles et spirituelles de Charlie', 3,
        '2023-01-03 12:00:00', 'French', null, 'Comedy'),
       ('David的旅行', '与David的旅行视频探索世界', 4, '2023-01-04 13:00:00', 'Chinese', null, 'Travel'),
       ('Emmaのファッション', 'Emmaのファッションのヒントやトレンドに触発される', 5, '2023-01-05 14:00:00', 'Japanese',
        null, 'Fashion'),
       ('Frank의 게임', 'Frank가 최신 게임을 플레이하고 리뷰하는 것을 보세요', 6, '2023-01-06 15:00:00', 'Korean', null, 'Gaming'),
       ('Grazia di bellezza', 'Impara a fare un trucco incredibile con Grazia', 7, '2023-01-07 16:00:00', 'Italian',
        null, 'Beauty'),
       ('Harry''nin Sihir', 'Harry''nin inanılmaz sihir numaralarına tanık olun', 8, '2023-01-08 17:00:00', 'Turkish',
        null, 'Magic'),
       ('Isabels Kunst', 'Sehen Sie Isabels schöne Gemälde und Zeichnungen', 9, '2023-01-09 18:00:00', 'German', null,
        'Art'),
       ('Jack''s Adventure', 'Join Jack''s thrilling adventure stories', 10, '2023-01-10 19:00:00', 'English', null,
        'Adventure');

INSERT INTO subscriptions (user_id, channel_id)
VALUES (1, 2),
       (1, 3),
       (1, 4),
       (1, 5),
       (1, 6),
       (2, 1),
       (2, 3),
       (2, 4),
       (2, 5),
       (2, 7),
       (3, 1),
       (3, 2),
       (3, 4),
       (3, 6),
       (3, 8),
       (4, 1),
       (4, 2),
       (4, 3),
       (4, 7),
       (4, 9),
       (5, 1),
       (5, 2),
       (5, 3),
       (5, 8),
       (5, 10),
       (6, 1),
       (6, 2),
       (6, 4),
       (6, 9),
       (6, 10),
       (7, 1),
       (7, 3),
       (7, 4),
       (7, 6),
       (7, 10),
       (8, 2),
       (8, 3),
       (8, 5),
       (8, 7),
       (8, 9),
       (9, 1),
       (9, 2),
       (9, 5),
       (9, 6),
       (9, 8),
       (10, 1),
       (10, 3),
       (10, 4),
       (10, 7),
       (10, 8),
       (11, 1),
       (11, 2),
       (11, 3),
       (11, 4),
       (11, 5),
       (12, 2),
       (12, 3),
       (12, 4),
       (12, 5),
       (12, 6),
       (13, 3),
       (13, 4),
       (13, 5),
       (13, 6),
       (13, 7),
       (14, 4),
       (14, 5),
       (14, 6),
       (14, 7),
       (14, 8),
       (15, 5),
       (15, 6),
       (15, 7),
       (15, 8),
       (15, 9);
