###saveByAuthorId
POST http://localhost:8080/channels?authorId=1
Accept: application/json
Content-Type: application/json

{
  "name": "Mortal Kombat",
  "short_description": "MK fun-club #1! All fans are welcome!!!",
  "main_language": "Spanish",
  "avatar": "clown.png",
  "category": "Video Games"
}

###updateById
PUT http://localhost:8080/channels/1
Accept: application/json
Content-Type: application/json

{
  "name": "RoboCop",
  "short_description": "RoboCop original movie fans",
  "main_language": "English",
  "avatar": "robotic.jpeg",
  "category": "Action Movies"
}

###findAllByFilter
GET http://localhost:8080/channels?name=Mortal&language=Spanish&category=Video&page=0&size=3&sort=name
Accept: application/json

###findDetailedInformationById
GET http://localhost:8080/channels/2
Accept: application/json
